package:
  name: truetype-tracer
  version: 12.01

source:
  path: ./

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  host:
    - freetype
    - pybind11
    - python

  run:
    - python
    - freetype

test:
  files:
    - py/
  requires:
    - pytest ==5.4.3
  commands:
    - pytest py/ -v

about:
  home: https://github.com/aewallin/truetype-tracer
  license: GPLv2
  license_family: GPL
  summary: Tool to produce font-outline geometry in various output formats such as DXF and GCode
  description: Tool to produce font-outline geometry in various output formats such as DXF and GCode
