name: Conda Package
on:
  push:
    branches:
    - '*'
jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['2.7', '3.6', '3.7', '3.8']
    steps:
      - name: "Clone"
        run: |
            git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git
      - name: "Install miniconda"
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: "Configure conda"
        run: |
            conda info
            conda config --add channels conda-forge
      - name: "Install conda-build"
        run: |
            conda install python=${{ matrix.python-version }} conda-build conda-verify
      - name: "Build"
        shell: bash -l {0}
        run: |
            mkdir dist/
            conda build ./ --output-folder dist/
      - name: "Upload package"
        uses: actions/upload-artifact@v1
        with:
            name: truetype-tracer-py${{ matrix.python-version }}-${{ matrix.os }}
            path: dist
